name: primobile


description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  numberpicker: ^1.1.0 #()
  flutter_slidable: "^0.5.4"   
  sqflite: any # ( lib para armazenamento de dados ao base de dados)
  http: any
  dio: ^3.0.9 #( lib responsavel por requests aos servidores)
  shared_preferences:  "0.5.7+3"
  connectivity: "0.4.8" #( lib responsavel por verificar tipo de conexao o dispositivo esta activo( Wifi ou Dados moveis))
  loading: ^1.0.2 #( lib para visualizar barra de progresso )
  intl: any
  flutter_speed_dial: ^1.2.5
  camera: ^0.5.8+5 # ( lib responsavel por captar imagem atraves da camera)
  image_picker: ^0.6.7  
  gallery_saver: ^2.0.1 #( lib responsavel buscar imagens armazenadas no disposivos como galeria e outros pontos)
  geolocator: ^5.3.2+2 #( lib para obter as posicoes geograficas do dispositivo)
  geocoder: ^0.2.1 #
  signature: ^3.1.1 #( lib para desenho, util para assinatura das encomendas pelos clientes)
  path_provider: ^1.6.11 #( retornar caminho do directorio onde a aplicacao esta instalada)
  cached_network_image: ^2.2.0+1 #( Visualizar imagem da rede e baixar para cache )
  dio_retry: ^0.1.9-beta #( Wrap da lib Dio para tentar nova conexao quando houver falha na conexao)
  flushbar: ^1.10.4  # mensagem snackbar 
  data_connection_checker: ^0.3.4 # verificar dados de conexao ( acesso a internet)
  marquee: ^1.5.2 # texto rolante

  
dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/jmr_logo.png
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
module:
    androidX: true 